name: Feature Request
description: File a feature request or propose an enhancement
title: "[ENHANCEMENT] <title>"
labels: [enhancement]
body:
- type: textarea
  attributes:
    label: What should this feature achieve?
    description: A concise description of the goal your feature is helping to achieve
  validations:
    required: true
- type: textarea
  attributes:
    label: How do you want to achieve said goal
    description: A description of your implementation idea
  validations:
    required: false
- type: textarea
  attributes:
    label: Why is this feature necessary?
    description: Name a few reasons to implement your feature
    placeholder: |
      1. It increases the level of automation...
      2. Contributes to the clean code rule...
      3. Improves the user experience...
  validations:
    required: true
