name: Question
description: Ask a question regarding all aspects of this project (Development, Usage, Documentation etc.)
title: "[QUESTION] <title>"
labels: [question]
body:
- type: textarea
  attributes:
    label: What is your question?
    description: A well thought out question
  validations:
    required: true
- type: textarea
  attributes:
    label: Further information
    description: More information if necessary (e.g. Configuration files, intentions etc.)
  validations:
    required: false
